### ISSUE TITLE
Can you provide a screen shot of the ZFS status on on the login screen?

### ISSUE THREAD

**Issue by arronmabrey** [alexwasserman/ZFSLoadCheck#1]
Would you be able to provide a screen shot of the ZFS status on on the login screen?

Thanks,
-- Arron

**Comment by sleepierbear** [comment]
![screen shot 2017-03-15 at 7 06 29 pm](https://cloud.githubusercontent.com/assets/6185574/23974618/8ba711e4-09b2-11e7-95c8-c70f175d7e2c.png)

**Comment by arronmabrey** [comment]
Thanks @alexwasserman. So this shows up on the login screen. That's pretty cool, I have never heard of the Apple API to build things like this before.
